version: "3"

services:
  database-postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "product-stock"
    restart: always
    volumes:
      - ./database-product-stock:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  database-product-stock:
